---
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.70.0/hugo_0.70.0_Linux-64bit.deb
  - sudo dpkg -i hugo_0.70.0_Linux-64bit.deb

script:
  - hugo

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: public
    target_branch: master
    repo: sandship-theorycrafters/sandship-theorycrafters.github.io
    on:
      branch: master