baseURL = "https://sandship-theorycrafters.github.io/"
languageCode = "en-us"
title = "Sandship Theorycrafters"
theme = "learn"

[outputs]
home = ["HTML","RSS","JSON"]

[params]
themeVariant = "red"

[[menu.shortcuts]] 
name = "Data"
url = "/data"
weight = 10


[[menu.shortcuts]] 
name = "<i class='fas fa-users'></i> Contributors"
url = "/contributors"
weight = 11

[markup.goldmark.renderer]
unsafe= true